### PR TITLE
Migrate to yarn

### PR DESCRIPTION
**Pull request by 7rulnik**

### CODE REVIEW

**Comment by iamakulov** [comment]
How yarn cooperates with npm? Imagine that Likely uses yarn, and a developer comes and installs a dependency with npm. What will happen the next time I run yarn?

**Comment by sadovnik** [comment]
> Imagine that Likely uses yarn, and a developer comes and installs a dependency with npm.

He will get dependencies that are differ from those listed in the lockfile.

> What will happen the next time I run yarn?

If a developer who uses npm will update some package, yarn's lockfile wont be updated. Next time a yarn user run `yarn install`, the dependencies will be re-resolved again and the lockfile will be updated.

Although the idea to support both npm and yarn users in development seems not much painful, but I recommend to stick to one of them just to avoid unnecessary problems.

**Comment by iamakulov** [comment]
@sadovnik Thanks for the clarification!

**Comment by iamakulov** [comment]
@7rulnik @sadovnik Thanks for the PR! As we now have `npm@5` with major performance improvements, I’ll close this in favor of `npm` (as `npm` is more common than `yarn`).

**Pull request closed without merging**
