### PR TITLE
Rename initate to initiate

### PR DESCRIPTION
**Pull request by gangstaJS**
Fix https://github.com/ilyabirman/Likely/issues/7

### CODE REVIEW

**Comment by volter9** [comment]
Thanks :)

**Comment by iamstarkov** [comment]
Yay, first breaking change! looking forward for likely 3.0

**Comment by volter9** [comment]
I didn't actually mentioned that `likeky.initate` or `likely.initiate` was part of public API. As I understand, Birman's initial intention of Likely was "simply install and forget".

Even 0.X Likely didn't had any public API (because to initiate dynamically likely widget, you had to invoke socialLikes method on jQuery element * gasp *). I'm planning onto writing documentation and making Likely even more modular (hello from OOP), which will lead to... Likely 3.0 (probably)

**Comment by iamstarkov** [comment]
> Birman's initial intention of Likely was "simply install and forget".

yeah, it was okay in the pre-npm era, but know we are using it in [scripts directly](https://github.com/iamstarkov/jsunderhood/blob/master/js/index.js#L1-L3). Looking forward for more modular likely! Great job 👍

**Comment by volter9** [comment]
> yeah, it was okay in the pre-npm era, but know we are using it in scripts directly

That's sooo embarrassing (I'm about `initate`), lol

> Great job 👍

Thanks :)

**Comment by volter9** [comment]
I decided to bring back the `initate` name. Yeah, it's misspelling of `initiate`, but there's couple of reasons why I did it:

* To avoid major release (Likely is only 2.0.4, there's more to come)
* To teach myself a lesson

That's pretty much it. @gangstaJS sorry for bothering you :smile:

**Comment by iamstarkov** [comment]
huh, you still can rename `initate` to `initiate`, but keep `initate` for backwards compatibility until next major release. i think it will be better

**Comment by volter9** [comment]
I didn't thought of that. That's genius! Thanks for the suggestion! :smile:

**Comment by gangstaJS** [comment]
@volter9 don't worry bro. It would be great to make from Likely react component.

**Pull request merged**
