### PR TITLE
Add the LinkedIn button

### PR DESCRIPTION
**Pull request by 350d**

### CODE REVIEW

**Comment by 350d** [comment]
Что-то надо с тестами доделать...

**Comment by vitkarpov** [comment]
> Что-то надо с тестами доделать...

Что именно? Вроде, добавленные тесты проходят

**Comment by 350d** [comment]
Я первый раз это делаю, не сразу все файлы обновил просто.

**Comment by iamakulov** [comment]
Hey @350d, thanks for the PR!

There’s a couple of issues with the icon though.
* The button has no icon (note the console error):
Screenshot
Looks like it’s caused by a double “M” in the beginning of the path. Could you please fix this?
* Can we make the icon corners rounder, just like in the Facebook/VK/Odnoklassniki icons?

As a side node: we decided to reject #16 which also proposed the button, but we’ve just re-discussed this with @ilyabirman, and we think the button is OK. Formally, we should accept the earliest PR, but `master` has diverged from #16 since submitting, so I think we’ll take this one. (Not really nice to Laurence (submitter of #16), but OK 😕)

**Comment by iamakulov** [comment]
Cool, thank you! I also removed the unnecessary `M` in the beginning of the path to fix the path rendering error. Pinging @ilyabirman for the final review.

**Comment by 350d** [comment]
Hello guys! @ilyabirman any progress here?

**Comment by iamakulov** [comment]
Ilya told me he approves the changes.

Merging this, thank you!

**Pull request merged**
