### PR TITLE
Added newsharecounts.com for Twitter counters

### PR DESCRIPTION
**Pull request by brugeman**
Hi, Ilya!
I'm building newsharecounts.com to replace Twitter share counts. Let's try it with your plugin? Will be happy to discuss or help or hear your feedback.

Спасибо!

### CODE REVIEW

**Comment by volter9** [comment]
Hello, there! Ilya isn't really visiting GitHub. I'm supporting this repository. Thank you in advance for your effort for building an API for twitter counters. :)

I pulled your fork's master branch to test your API, but it doesn't seem to display correct count values. Birman's homepage had something like 127 twitter shares before Twitter took down their counter API. Now it's 0 :)

Could you explain how does your service works?

**Comment by brugeman** [comment]
Hi, Evgeny! Great to hear from you!

It works this way:
- a request to Search API is made to get all tweets mentioning the domain
name
- tweets are parsed, urls are extracted
- all urls are crawled to expand shortened urls and discover canonical urls
- shares are counted for each url

This means that we only have access to 7 days of history that Twitter's
Search API provides, from the day you start tracking the website. All
previous share counts are permanently lost, if Twitter does not change it's
mind or you don't have them in some kind of local cache like some WP
plugins do.

I have actually collected share counts for around 1 billion urls before
they shut it down, but that's still a tiny fraction of all the Web, so most
websites will start from zero.

The only guys I know about who have more data are BuzzSumo with their
Chrome extension, but they pay 1$M per year to Gnip for access.

Hope that helps.

--
Artur


2015-12-10 0:12 GMT+05:00 volter9 <notifications@github.com>:

**Comment by volter9** [comment]
Wow, that's sounds like epic amount of work. Just wonder, how fast would your service parse twitter tweets after I pressed button tweeted on twitter?

**Comment by brugeman** [comment]
I have 1 request per 5 seconds per account rate limit. If you have 1 site
tracked, I check it every 5 seconds. Plus some seconds while Twitter adds
the tweet to search index. Plus some seconds while I crawl the url if it's
new. Plus some seconds for my system to do some background work (this part
will soon be removed). Should be quite close to real time, 10-30 seconds
after tweet now, will be 5-10 seconds when I finish real-timier part.

The more sites you have, the less often I check each of them.

If you feel like something is not working properly on my side - drop me a
line.

Thanks!

2015-12-10 0:43 GMT+05:00 volter9 <notifications@github.com>:

**Comment by volter9** [comment]
Well, I decided to test and shared on Twitter on the `test.html` like five minutes ago, and there's still no `1` on the counter. Maybe, I doing something wrong?

**Comment by brugeman** [comment]
Which url did you share?

I used Search API to look for "volter9 github io", nothing is there. If you
search on site
https://twitter.com/search?f=tweets&vertical=default&q=volter9%20github%20io&src=typd
it does return some results but those are older than 7 days (Twitter search
on site can give much more data than search api). Maybe you shared another
domain?



2015-12-10 1:01 GMT+05:00 volter9 <notifications@github.com>:

**Comment by brugeman** [comment]
Btw, have you tweeted http://volter9.github.io/test.html ?

That page returns 404, and that's probably the reason why Twitter did not
include this tweet in the search results. It's own bot crawls all tweeted
urls to expand them.

I checked share counts of your home page:
http://public.newsharecounts.com/count.json?url=http://volter9.github.io/

It was zero. I tweeted it, and the counter incremented in less than 10
seconds.

If you tried different domain, keep in mind that you have to add the site
to tracking before you can see results. Just 'sign-up' with another domain
(it will be added to your account), or add site here:
http://app.newsharecounts.com/

2015-12-10 6:50 GMT+05:00 Artur Brugeman <brugeman.artur@gmail.com>:

**Comment by volter9** [comment]
Sorry, I forgot to mention which URL I shared. I shared Birman's homepage: http://ilyabirman.ru/ 

> If you tried different domain, keep in mind that you have to add the site
to tracking before you can see results. Just 'sign-up' with another domain
(it will be added to your account), or add site here:
http://app.newsharecounts.com/

Oooh, I didn't knew that, so basically, before attaching counter, I have to register my website on your service. Gotcha! :)

I'll contact Birman and get agreement on integrating your counters. Thank you for your work! :)

**Comment by brugeman** [comment]
Great, thanks!

I'm still investigating the best way to inform users like you who
forgot/didn't know they need to register first. This will help to resolve
such issues w/o falling back to support requests. I'll let you know when
something is ready.

Best wishes!

2015-12-10 12:25 GMT+05:00 volter9 <notifications@github.com>:

**Comment by volter9** [comment]
@brugeman, I'm sorry to inform you, but Birman doesn't want to use your service. However you may distribute a fork of Likely with addition of your Twitter counter provider. Don't forget to `gulp build` every time you commit, though.

**Comment by brugeman** [comment]
Thanks anyway, Evgeny!

2015-12-11 14:57 GMT+05:00 volter9 <notifications@github.com>:

**Pull request closed without merging**
