### PR TITLE
[#60] Make ESLint check the Gulpfile and other infrastructure files

### LINKED ISSUE #60: Configure ESLint to also check the infrastructure JS files
Following https://github.com/ilyabirman/Likely/pull/58#discussion-diff-63279864.

Currently, ESLint checks and fixes only files located in the `source` directory. It’d be great if the tools configuration files (for example, `gulpfile.js`) were also validated. As a probable solution, we should configure ESLint to check all `.js` files except those located in `release` directory.

PRs are welcome. Current `gulpfile.js` won’t be validated by ESLint, so it should also be fixed to correspond to the linting rules.

### PR DESCRIPTION
**Pull request by iamakulov**
Closes #60.

### CODE REVIEW

**Comment by iamakulov** [comment]
@vitkarpov

**Comment by vitkarpov** [comment]
Great! 👍 Seems eslint demands to fix gulpfile now :)

**Comment by iamakulov** [comment]
Yup, I forgot to check the code style in the last commit :–)

**Comment by vitkarpov** [comment]
👍

**Pull request merged**
