### PR TITLE
Hides random functions behind the likely namespace

### PR DESCRIPTION
**Pull request by vitkarpov**

### CODE REVIEW

**Comment by vitkarpov** [comment]
@iamakulov

**Comment by vitkarpov** [comment]
> likely seems like a pretty generic name that could be overridden by an occasion

Are you sure? `likely` is our namespace, where the whole lib lives.

**Comment by iamakulov** [comment]
But there're other usages of `likely` outside of other library because it's a generic English word. E.g. someone could call a global variable with this name. That's why I'm for a more specific name.

**Comment by vitkarpov** [comment]
Yeah, likely could be used as commonjs module, I get it. `_likelyCallbacks ` is a good choice :)

**Comment by iamakulov** [comment]
@vitkarpov, could you please do the changes here? Or please tell if you’re going to return to this later, I’ll keep this opened.

**Comment by vitkarpov** [comment]
Yeah, sure. I'll finish this.

**Comment by vitkarpov** [comment]
@iamakulov done, but for some reason tests are failed, not only in this pr. Seems like a problem with Travis, 'cause it started to reproduce recently

**Comment by iamakulov** [comment]
Thanks! We'll deal with the tests later

**Pull request merged**
