### PR TITLE
Add info about CDN

### PR DESCRIPTION
**Pull request by 7rulnik**

### CODE REVIEW

**Comment by vitkarpov** [comment]
👍

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/issues/71

**Comment by iamakulov** [comment]
@7rulnik, thank you for your help! However, I believe people are more likely to look for the CDN links [in the `Get` section](https://github.com/ilyabirman/Likely#get), so I’d rather put the CDN information there. Could we update the PR so the info is more reachable?

**Comment by iamakulov** [comment]
Thank you 👍

**Pull request merged**
