### PR TITLE
(fix): defines cache for likely callbacks

### PR DESCRIPTION
**Pull request by vitkarpov**

### CODE REVIEW

**Comment by iamakulov** [comment]
Will this work when the library is imported as a CommonJS module? The CommonJS build doesn’t include the `likely.js` file, as far as I remember

**Comment by vitkarpov** [comment]
Good point! I guess it doesn't, we don't have a test or demo page, so I missed it. I think I have to move this into `index.js`.

**Comment by iamakulov** [comment]
I’d suggest moving it into `dom.js`, where this property is actually used (but the choice is yours)

**Comment by vitkarpov** [comment]
Yep, you're right. Fixed! :)

**Pull request merged**
